on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "staging"


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        run: echo "Deploying the application..."
